gunk/gunk

README.md, examples/util/doc.go, go.mod, go.sum, loader/loader.go, main.go, main_test.go
go/build is deprecated, since it was designed before Go modules. Its
replacement in most cases, including ours, is go/packages.
Start using it to locate packages, which is the same reason we were
using go/build for. This has two major advantages, besides removing a
deprecated dependency:
* Module support. We no longer depend on GOPATH to resolve imports and
find other Gunk packages. Moreover, when using a module, missing deps
will be added to go.mod via the 'go list' invocations.
* Pattern support. go/build did not resolve patterns like ./..., but
go/packages (again, via 'go list') does.
Fixes #11.
=> all: replace go/build with go/packages

.travis.yml, loader/loader.go, tools.go
Start using the full power of modules on CI. To do that, we must drop Go
1.10, as it only has minimal support for them.
While at it, drop tip too, as it's a moving target and not very useful
to enforce on CI. I develop on tip, so if an upcoming Go release were to
require changes in Gunk, we'd notice anyway.
=> CI: fix build via modules

loader/loader.go, main_test.go, testdata/generate/echo.gunk
Initially I wanted to get this done independently in a single commit,
but it turns out to be trickier. We need to know all protobuf package
names upfront, so that we can write fully qualified names properly.
I had another PR in the works that revamped package loading and
introduced the notion of a "gunk package", so that should be merged to
help with this task. So it's best to merge this piece first, and then
finish off the feature once the loading refactor is merged.
Updates #44.
=> loader: preparation for custom proto package names

loader/loader.go, main_test.go, testdata/scripts/empty.txt
Add a gunkPackage structure, which is a wrapper over packages.Package
which adds GunkFiles. This lets us reason about loading Gunk packages
better, instead of loading Gunk files in an ad-hoc manner.
Now, all the information about what gunk files to translate is known
upfront, before any translation happens.
This lets us handle certain edge cases better, such as being given Go
packages with zero gunk files. Added test cases for those.
=> loader: improve loading gunk packages

generate/generate.go, generate/proto.go, loader/loader.go, main.go, main_test.go
In preparation for multiple commits. The fmt subcommand will reuse the
package loading code, so leave that in loader.
For #37.
=> generate: split the generate code

convert/convert.go, go.mod, go.sum, main.go
Add a convert command that will convert proto files to gunk files. The
convert command takes in a single .proto file, and converts it to a
.gunk file.
The converter will convert most proto specific declarations; enums,
messages, services, package and package options. Most message field
types should be converted as well, including the basic (scalar) proto
types and maps and arrays.
Any nested enums in messages are converted to top level declarations
because Gunk doesn't currently support nested structures.
The google http annotation is converted to +gunk equivalant.
We use github.com/emicklei/proto to parse the proto file, rather than
using protoc, because protoc doesn't keep the comments when generating a
proto filedescriptor.
=> convert: started proto to gunk converter

format/format.go, main.go, testdata/scripts/fmt.txt
For now, all we do iss format the Go syntax. Formatting of our extra
Gunk additions, such as the +gunk comment expressions, will come later.
Updates #37.
=> format: add first version of 'gunk fmt'

generate/generate.go, generate/proto.go
We were being too clever with the transform functions. Doing it the
trivial way is actually much simpler.
Most importantly, this will let us have more complex logic to extract
the +gunk tags, which we need for #35.
=> generate: simplify handling of doc strings

loader/loader.go, testdata/scripts/eval.txt
For now, do syntax errors only. Left a TODO to update the positions in
the returned ast.Expr, which will then fix type-checking errors. Leaving
that for a later time.
Fixes #35.
=> loader: accurate position info for gunk tag errors

main_test.go
This can cause issues in a system like mine, where /tmp is a ramdisk:
link [...]/.gunkconfig /tmp/[...]: invalid cross-device link
=> test: don't use os.Link to place files in tests

convert/convert.go, format/format.go, generate/generate.go, main.go, main_test.go
generate.Run is better than generate.Generate.
=> all: remove stutter from subcommand funcs

examples/util/.gunkconfig, generate/generate.go, go.mod, go.sum
In each 'generateProtoc' run we modify the protofile name, however, this
was a pointer, and was changing the value for all runs of
'generateProtoc' and 'generatePlugin'. Make a dumb copy of the protofile
before we use it.
Updated the ini parser to a forked version that handles multiple
section names, and getting keys from the different sections, correctly.
I have created a PR upstream for [ini](https://github.com/knq/ini/pull/1), until then we can use my fork of the ini parser.
=> generate, mod: copy pointer values before updating them

config/config.go
Gunkconfig will now handle the shorten version of a generate sections.
```
[generate js]
```
will become:
```
[generate]
protoc=js
```
=> config: support for shorten generate section

format/format.go, testdata/scripts/fmt.txt
This is a bit tricky, since we need to extract the tag, parse it, print
it, and put it back in the comment without messing up the relative
positions.
Fixes #37.
=> format: also reformat +gunk tags in comments

README.md, config/config.go, examples/util/v1/.gitignore, generate/generate.go, testdata/scripts/config.txt, testdata/scripts/config_default.txt, testdata/scripts/config_parent.txt, testdata/scripts/config_with_out.txt
Look for a .gunkconfig in each gunk package, if one isn't found then
look in each parent to see if one exists. The path for generators to
output generated files will be the following:
- Next to the *.gunk files, if no 'out' key specified (the default)
- Wherever the 'out' key specifies. If the path is absolute, we use
that path. If it isn't absolute, then we join the 'out' with the
directory containing the .gunkconfig
Added 'examples/util/v1' which is where the files should be generated.
Closes #82
=> config,generate: look for gunkconfig in each gunk package

generate/generate.go, loader/loader.go, testdata/scripts/envs.txt
We were skipping the error from loading proto dependencies, which could
lead to confusing errors down the line or even panics.
Add a test too. While at it, improve that error's context.
Fixes #85.
=> generate: avoid confusing error if protoc errors

generate/generate.go, testdata/scripts/repeated_function_param.txt
Proto doesn't allow you to have repeated function parameters. However,
it is easy to forget when Go and other languages allow repeated function
parameters.
We now return an error if a functions input or output parameter is a
repeated structure.
Closes #81
=> generate: error on array function parameters

generate/generate.go, go.mod, go.sum, loader/loader.go, log/log.go, main.go, testdata/scripts/generate_flags.txt
Added '-x' and '-v' to 'gunk', they behave similar to Go. '-x' will
print any commands that are run, these currently include 'protoc',
'protoc-gen-*' and 'ls' commands. '-v' will print when a gunk package
has been generated, this currently also doubles as a 'verbose' like
flag, which will print out any stderr from a command.
Closes #91
=> all: added debug information controlled by command line flags

main_test.go, testdata/scripts/config_noconfig.txt
To make the test scripts completely independent and reproducible, each
test runs in its own directory, HOME, and Go environment, including
module cache.
This means that loading any Gunk packages that import packages from the
internet like gunk/opt will need to download them every time. This can
be slow, since downloading a module from GitHub requires a few http
roundtrips and won't be cached between test runs.
In the long run, we should use something like
github.com/rogpeppe/go-internal/goproxytest to provide a static module
proxy to the tests, so they can load the third packages we want in a
predictable way.
For now, simply removing the unnecessary import brings down the run time
of 'go test' from ~2.4s to ~0.8s on my laptop.
=> testdata: remove unnecessary module deps

loader/loader.go, testdata/scripts/format.txt
For now, until the upstream issue is resolved.
Fixes #59.
=> loader: add workaround for loading zero patterns

generate/generate.go, testdata/scripts/generate_fileoptions.txt
Allow the user to set '+gunk' tags in the package comment for
controlling the proto options. Currently only the options defined in
'github.com/gunk/opt/opt.gunk' are supported, these are:
- Deprecated
- JavaPackage
- JavaMultipleFiles
Updates #104
=> generate: configurable gunk options

config/config.go, format/format.go, generate/generate.go, loader/loader.go, testdata/generate/all.pb.go, testdata/generate/all.pb.gw.go, testdata/scripts/eval.txt, testdata/scripts/format.txt
We were using the loader for two purposes. The simpler was the
formatter's use case, where we only need to parse the given packages.
The second and more complex is the generator's. It needs to parse the
given Gunk packages, all of their Gunk dependencies, and type-check all
of them including their gunk tags.
Before, all this extra work was done in the generator package. This
worked okay, but led to complex lazy loading and type-checking all over
the place.
Instead, have the loader package mirror go/packages more closely. By
default it will only do what the formatter needs. But if Types==true, it
will also typecheck the Gunk packages and their gunk tags, and
consequently do the same for all their transitive Gunk dependencies.
All the loading is entirely in the loader package, and the …
=> loader: perform all gunk loading here

go.mod, go.sum, main_test.go, testdata/mod/github.com_gunk_opt_v0.0.0-20181129161359-767b03a66301.txt, testdata/scripts/generate_languages.txt, testdata/scripts/generate_options.txt
A 'go test' with the cache warm now takes ~0.7s instead of ~4s on my
laptop.
The command used to "vendor" the module in this static GOPROXY was
github.com/rogpeppe/go-internal/cmd/txtar-addmod:
txtar-addmod -all testdata/mod github.com/gunk/opt@latest
Finally, we need to add the same version requires to each test go.mod
file, so that we don't have to figure out which version is latest at
each test run.
Fixes #119.
=> testdata: use a static GOPROXY for the scripts

loader/loader.go, testdata/scripts/config.txt, testdata/scripts/config_merge.txt, testdata/scripts/config_noconfig.txt, testdata/scripts/config_projectroot.txt, testdata/scripts/config_with_out.txt, testdata/scripts/empty.txt, testdata/scripts/envs.txt, testdata/scripts/eval.txt, testdata/scripts/format.txt, testdata/scripts/format_missingnumbers.txt, testdata/scripts/generate_flags.txt, testdata/scripts/generate_languages.txt, testdata/scripts/generate_options.txt, testdata/scripts/generate_unused_imports.txt, testdata/scripts/repeated_function_param.txt
loader: remove the need for doc.go files
We needed these files to make Gunk packages always be Go packages too.
Otherwise, if a directory has zero Go files, a command like 'go list
./...' would skip them.
However, that was a terrible hack to work around an implementation
detail, and it should have never been visible to the user. Requiring the
user to add doc.go files is unnecessary and a bit annoying.
For now, work around the issue by adding temporary Go files to all Gunk
packages that need them. Use randomized filenames, so that concurrent
gunk calls don't step on each other.
Since we can't know what directories a list of patterns should expand to
before adding these temporary Go files, we do the next best thing - we
walk the tree, looking for Gunk packages with zero Go files. We do this …
=> loader: remove the need for doc.go files

testdata/scripts/config_projectroot.txt
We were testing for a '.git' directory instead of a 'go.mod' file in the
test for when 'go.mod' is the project root. Changed '.git' to 'go.mod'
to correctly test the case where a 'go.mod' file is the project root.
Fixes #121
=> tests: fix config_projectroot test

generate/generate.go, testdata/scripts/generate_mappings.txt
Added the following missing type conversions from gunk (go) -> proto:
- uint -> FieldDescriptorProto_TYPE_UINT32
- uint32 -> FieldDescriptorProto_TYPE_UINT32
- int64 -> FieldDescriptorProto_TYPE_INT64
- uint64 -> FieldDescriptorProto_TYPE_UINT64
- float32 -> FieldDescriptorProto_TYPE_FLOAT
- float64 -> FieldDescriptorProto_TYPE_DOUBLE
Fixes #115
=> generate: add missing type mappings

main_test.go
The script tests were running in parallel among themselves already,
which is built into testscript. However, they weren't running in
parallel to TestGenerate.
TestGenerate and some of the script tests are the slowest without maxing
out on cpu, so this reduces 'go test' time on my laptop on battery from
~2.4s to ~1.4s.
TestGenerate writes to files in testdata/generate, but that's still fine
for t.Parallel - since that means it can run in parallel with other
parallel tests, but not itself.
=> all: run tests in parallel

main.go, main_test.go, testdata/scripts/cmds.txt
All the go tools accept this flag, so we should too.
Fixes #129.
=> all: add -h as a short version of --help

config/config.go, testdata/scripts/generate_languages.txt
'protoc-gen-*' generators can now be used as shortened generate sections
in the gunkconfig. Previously, we just assumed that any
'[generate <x>]' in the gunkconfig should be passed through as 'proto --<x>_out'.
Now, we can have '[generate go]' and this will check for a 'protoc-gen-go' binary,
if it exsists that is used, otherwise it falls back to being passed
through to protoc.
Fixes #96
=> config: allow shortened generate sections for protoc-gen-*

README.md
Remove the "required installs" step. We can easily merge the Go
dependency with the install step. And the protoc dependency will be
dropped soon, as gunk will download it at run-time if necessary.
Pointing at the issue tracker is also not terribly useful, as GitHub is
very ubiquitous these days.
Finally, cut the help output, as we don't want to keep that up to date
forever, and we don't want the README to be that long. The user can
easily get the help text themselves if needed.
And some other minor adjustments, like removing an unnecessary .git
extension and joining the GO111MODULE line with another.
=> README: minor edits to be less verbose

generate/generate.go
Attempt to sort the FileDescriptorSet in an order such that any proto
files without dependencies are first in the list, and the rest are at
the end.
Use a fairly dumb, but simple approach to determine which protofile's
depend on others. We can use this approach because we don't load that
many protofile's, and the ones we do load don't depend on each other.
This is required to fix an issue with the protoc nodejs grpc generator,
which seems to expect the protofiles to be in an order where any
depdendent protofile's are earlier on in the list.
Fixes #137
=> generate: sort protofile dependencies

convert/convert.go, testdata/scripts/convert.txt
The code for converting the proto service methods into Gunk interface
methods was inside the incorrect forloop and therefore wasn't getting
called.
Also fix an issue with not outputting the empty parameter correctly in
both the request and returns parameter.
Updates #141
=> convert: output service methods correctly

dump/dump.go, generate/generate.go, main.go
Added a new 'dump' command that outputs a single Gunk package's
FileDescriptorSet (as specified in descriptor.proto). This should help
when trying to debug the differences between what Gunk and Protoc
generate.
The dump command will output in 'raw' format as default (the same as
protoc -o), but can be specified to dump as 'json' format. The output
will be sent to stdout by default, but can also be written to a file.
Fixes #136
=> dump: command that outputs filedescriptorset

README.md, convert/convert.go, go.mod, go.sum, main.go, testdata/scripts/convert_files_and_folders.txt
Accept a list of files and folders for the convert command and run
these through the converter. Only '.proto' files are converted to Gunk
files.
Updated readme.
Update github.com/emicklei/proto to 1.6.8.
Fixes #134
=> convert: allow proto files and folders

config/config.go, testdata/scripts/config_global.txt
Allow a global 'out' parameter to be set. Each '[generate]' section will
inherit this global 'out' parameter unless the '[generate]' section has
the 'out' parameter set.
=> config: global 'out' parameter

convert/convert.go, testdata/scripts/convert.txt, testdata/scripts/convert_fileoptions.txt, testdata/scripts/convert_files_and_folders.txt, testdata/scripts/convert_iota.txt
Updated convert to convert proto 'FileOptions' to the corresponding Gunk
annotations.
While doing this, it was required to keep a record of which
imports of Gunk annotations are being used. Now we only output imports
that are actually in use, or no imports at all if there are no imports.
Updates #143
=> convert: proto fileoptions

convert/convert.go, generate/generate.go, log/log.go, testdata/scripts/envs.txt, testdata/scripts/generate_flags.txt, testdata/scripts/generate_mappings.txt, testdata/scripts/generate_unused_imports.txt
Most programs, upon erroring, will only include the reason in stderr.
This led to some confusing error messages on common exec errors, such as
the binary missing in $PATH:
error: error executing protoc-gen-print: , exec: "protoc-gen-print": executable file not found in $PATH
To fix this, don't include stdout in error messages. But do include
stderr if it wasn't already written out directly because of the verbose
flag.
Also make the log package output to os.Stderr by default, making it
configurable. Logging should generally go to stderr, as stdout is
reserved for the result or output of a program or command. This also
means that a plugin's stderr will always go to stderr if it errors, even
if gunk is run in verbose mode.
Finally, clean up the scripts files to not mix tabs and spaces …
=> generate: don't include stdout when an exec errors

convert/convert.go, testdata/scripts/convert_errors.txt
Add the filename to error messages in gunk convert. This is now required
because gunk convert can handle more than a single proto file.
Change the pkgOpts to use proto.Option rather than a custom struct so
that we don't lose positional information about an option, and can error
correctly on that options.
Fixes #154
=> convert: include filename in errors

convert/convert.go, testdata/scripts/convert_unhandled_options.txt
Print warnings for unhandled proto options when using gunk convert:
- message options
- field options
- enum options
- enumvalue options
- service options
- method options
This should only be temporary until we handle the missing proto options,
but this should at least give the user some warning that some of the
proto options they are using won't be converted.
Don't include newline in error message for gunk convert.
Updates #143
=> convert: warn on unhandled proto options

generate/generate.go, main_test.go, testdata/protoc-gen-strict/main.go, testdata/scripts/generate_fileorder.txt
First, add a test script that uses a custom Go generator which checks
that the ProtoFile slice is sorted topologically. We've found in the
past that some generators require that, so the easiest way to add a
regression test is to implement a dummy generator which checks that
property.
Second, redo the topological sort to support all inputs. The old code
only split the list of files in two chunks, which may quickly break if
one has multiple levels of package dependencies.
There are efficient algorithms we could have chosen which would have
taken over fifty lines of code, but a much simpler quadratic algorithm
will do the job for the foreseeable future in under twenty.
Finally, remove the sorts of files by name. We no longer have multiple
proto files per Gunk package, so we don't care about …
=> generate: refactor how we sort proto files

README.md
There's no "protobuf" command, so we shouldn't backquote that. Use
better names instead.
There were also some wording mistakes, like "protobuf's, protoc" and
"gunk aims is to provide". Fix those.
=> README: slightly improve intro wording

generate/generate.go, testdata/scripts/generate_enum.txt, testdata/scripts/generate_options.txt
If a gunk comment only contained a gunk tag, don't keep it around as a
documentation comment in the generated code.
Add a test, and update generate_options.txt to be more permissive with
the whitespace. Since we removed a few bad comments there, gofmt now
aligns the field types, so a few spaces have been introduced.
Fixes #110.
=> generate: discard empty doc comments

generate/generate.go, go.mod, go.sum, testdata/scripts/generate_errors.txt, testdata/scripts/repeated_function_param.txt
Start recording the current position of the token being evaluated. We
then use the recorded position when priting out errors, so errors should
now include 'filename:line:column' at the start of all generate errors.
Fixes #169
=> generate: add positional information to errors

generate/generate.go, go.mod, testdata/generate/.gunkconfig
We are sending an empty string to protoc generators for the 'Parameter'.
This was causing issues with 'protoc-gen-grpc-gateway'. We now send
'nil' when there is no parameters found in the config for a generator.
Fixes #165
=> generate: send 'nil' rather than empty string to protoc generators

generate/download.go, generate/generate.go, log/log.go
The log package only needs to care about printing lines, and whether
some lines are verbose or not. We also have a wrapper for exec.Cmd which
is handy. Everything else is redundant.
This can be shown by how halving the number of APIs in the log package
doesn't make the rest of the code any more complex. If anything, the
code using the log package is now simpler to follow.
=> log: simplify package

loader/loader.go, testdata/scripts/loader_repeated_sequence.txt
If we detect the same sequence number used in a struct, return an error
pointing to the duplicated sequence number.
Fixes: #182
=> loader: error on repeated sequence numbers

main.go, testdata/scripts/cmds.txt
For better or worse, kingpin's Terminate function needs to actually exit
kingpin's control flow. Since we can't use os.Exit because of
testscript, our only other option is a custom panic type.
One symptom of that bug was that 'gunk -h' displayed the help text twice
- once for the help flag, and a second time since no subcommand was
given.
Fix that, and add a regression test.
=> fix app.Terminate to properly terminate kingpin

.travis.yml, generate/download.go, generate/generate.go, main.go, testdata/scripts/download.txt
Added 'gunk download' command which will download any required, but
missing, tools or packages. Currently, this will only download protoc.
Added test for downloading protoc.
Changed CI to download protoc using 'gunk download'.
Fixes: #177
Fixes: #175
=> download: gunk download command

format/format.go, generate/generate.go, loader/loader.go, loader/visit.go, testdata/scripts/dump.txt, testdata/scripts/loader_typeerror.txt
go/packages only uses its error return for fatal errors, such as when
the query is malformed or when it cannot call 'go list'.
All other errors, such as typecheck errors, are attached to packages.
This is because loading can often continue in the face of these
non-fatal errors, and it's useful for tools to report many errors at
once.
Do the same in our loader package. On the upside, this removes
ValidateError, removes a few error returns, and consolidates the API
with go/packages.
The only disadvantage is that we now need to port PrintErrors from
go/packages, which also requires Visit. But it's likely we were going to
need Visit sooner or later, anyway.
=> loader: rethink package loading errors

go.mod, go.sum, loader/loader.go, testdata/scripts/loader_error.txt, testdata/scripts/loader_typeerror.txt
Add positional information to error messages produced by loader.
Moved 'validatePackage' to 'Loader' so the FileSet is populated and
accessible.
Closes #169
=> loader: positional information to error messages

convert/convert.go, loader/loader.go, testdata/scripts/convert_invalid_package_name.txt
If the package name of the proto file being converted isn't a Go
compatible package name, e.g: contains a ".".
Updates #146
=> convert: error if package name isn't Go compatible

convert/convert.go, format/format.go, loader/loader.go
We can use an assignment in a type switch, so that we don't have to use
type assertions further down in each switch case.
And IsIdentifier was added by mistake.
=> all: simplify type switches, remove IsIdentifier

loader/proto.go, testdata/scripts/convert_options.txt, testdata/scripts/convert_unhandled_options.txt
When loading and converting a proto file to a gunk file, use named
imports for imports that are likely to have the same package name.
The first time an import is seen, that gets to keep its package name.
The next time an import with that package name is encounted, that
is given a named import.
Updates: #143
=> loader: named imports and message options

generate/generate.go, loader/proto.go, testdata/scripts/convert_nested_messages.txt
Protocol buffer supports nested message, as described [here](https://developers.google.com/protocol-buffers/docs/proto3#nested)
This PR adds the support of nested message in gunk by: 
- adding a case for `proto.Message` type in `handleMessage` that calls itself
- remove `.` from the declaration type of a nested message referenced outside of its parent
Fix issue when generating from a `.gunk` with struct containing struct from the same package
=> convert: handle nested message

loader/proto.go, testdata/scripts/convert_duplicates.txt, testdata/scripts/convert_nested_messages.txt
- Ensure that there is no duplicate between nested and top-level message. 
- Rename nested message to `Parent_Child` instead of `Child` when creating the top level struct
=> convert: handle duplicate message

.travis.yml, loader/loader.go, testdata/scripts/config_projectroot.txt, testdata/scripts/generate_errors.txt, testdata/scripts/generate_mappings.txt
Go 1.13 has GO111MODULE=on as a default, so some of the tests now
started failing. For example, config_projectroot.txt ran some 'go list'
commands with no go.mod file underneath, meaning that 1.12 was falling
back to GOPATH mode.
First, make those errors more obvious; before they used to be just:
error: lstat : no such file or directory
This was because 'go list -m -f={{.Dir}}' would return an empty string,
so we'd try to filepath.Walk an empty path.
Second, add go.mod files where appropriate in the tests. Not having
these go.mod files was likely an oversight, as they are needed to
properly load packages in module mode.
Third, modify the 'gomod' test case, as it's not possible to load a
module's packages from another module via relative paths.
=> fix running some of the tests on Go 1.13

testdata/scripts/download.txt
Until we can rewrite it to not require internet and be faster. Speeds up
'go test' on my laptop from 4-8s to ~1s.
=> skip the download test script for now

generate/generate.go, loader/loader.go, testdata/scripts/generate_nested_message.txt
We were leaving pkg.Name as a TODO when loading single files. And this
was usually fine, except when generating lone Gunk files under some
circumstances.
Cédric ran into one of those in the added test script, which he
supplied. Fix the bug in the loader by grabbing the package name from
all the files, much like cmd/go does.
Finally, remove the ProtoName=="" workaround that was added recently
because of this bug.
=> loader: set up Name and ProtoName when loading files

README.md, config/config.go, convert/convert.go, generate/generate.go, loader/loader.go, loader/proto.go, testdata/scripts/convert_files_and_folders.txt, testdata/scripts/convert_import.txt, testdata/scripts/convert_import_missing_gopkg.txt, testdata/scripts/convert_import_no_gunkconfig.txt, testdata/scripts/convert_relative_import.txt
Add `[convert]` section to handle import when converting `.proto` to `.gunk`:
If `import_path` is provided within that section, gunk will pass this path to protoc in `LoadProto` method.
proto files passed will be parsed to retrieve `go_package` option value and added as import in resulting gunk file
Fix #198
=> convert: handle import proto files

convert/convert.go, generate/download.go, generate/generate.go, go.mod, loader/proto.go, main_test.go, testdata/generate/go.mod
Use bytes.Buffer when we need bytes.
Less string handling with types.
Finally, %s already calls the String method, so we can avoid the
repetition.
=> all: various cleanups

loader/proto.go, testdata/scripts/convert_complete_swagger.txt
We can't directly range over a map's keys, as their order is randomized.
This means we can make the swagger test much stronger and simpler.
=> make printing of annotations deterministic

main_test.go, testdata/mod/github.com_golang_protobuf_v1.3.1.txt, testdata/mod/github.com_gunk_opt_v0.0.0-20190514110406-385321f21939.txt
gunk/opt was invalid, as reported by sum.golang.org; go.mod had been
tampered somehow. Re-add it.
We also need to be able to resolve github.com/google/protobuf. The
module is massive, and txtar-addmod would add ~1.5MiB in a file.
Fortunately, we just need to resolve the module, and not build it.
So a stub txtar file is enough. Turn off sum.golang.org, as it
(correctly) reports that the source is different. We don't care.
With these changes, 'go test' passes on 'go version devel +d97bd5d07a
Sat May 25 22:38:01 2019 +0000 linux/amd64'.
=> testdata/mod: fix the module copies

generate/generate.go, loader/proto.go, reflectutil/setter.go, testdata/scripts/convert_complete_swagger.txt, testdata/scripts/convert_options_openapiv2.txt, testdata/scripts/generate_complete_swagger.txt, testdata/scripts/generate_options_openapiv2.txt
Only tags, summary and description were handled from the operation model
This commit adds the remaining fields
- Add missing fields for Operation, convert and generate
- Add missing security field in Swagger, convert and generate (the security field is the same as in operation, so I took the opportunity to add it in swagger as well)
=> all: handle the complete Operation definition from swagger

.travis.yml, generate/generate.go, loader/proto.go, reflectutil/setter.go
We can move a lot of work to this helper function. For example, grabbing
the name from an identifier key, the value from a literal, or unquoting
a value string.
Also make it support converting types, so we can assign an int32 value
to an enum field, since it has a named type.
We can also remove many uses of snaker; the field search was already
case-insensitive, so removing all underscores is all that we need to
make it work.
This means we can drastically simplify and unify many uses of SetValue,
making the meat of the code simpler and less verbose.
=> reflectutil: move more reflect magic here

convert/convert.go, generate/generate.go, loader/proto.go, reflectutil/setter.go
Gets rid of almost all the rest of the boilerplate code. The only pieces
left are because SetValue can only deal with struct fields.
While at it, unindent and simplify fromStructToAnnotation.
Finally, make the final section of valueFor parse strings alone,
handling the special enum case separately.
=> reflectutil: support all maps and enums

docgen/docgen.go, docgen/generate/generate.go, docgen/pot/pot.go, generate/generate.go, testdata/scripts/extract_append.txt
Add append mode in gunkconfig to allow appending service/annexe
documentation into an existing all.md. The same for the translations
messages.pot file.
While at it, change AddTranslations to AddTranslation as it was
never used with an array of translations
=> docgen: add append mode for messages.pot and all.md

.travis.yml, README.md, config/config.go, convert/convert.go, generate/download.go, generate/generate.go, go.mod, go.sum, main.go, testdata/generate/go.sum, testdata/scripts/config_protoc.txt, testdata/scripts/download.txt
Add a protoc config section to allow users to pin a specific protoc
version. Make the path configurable as well- gunk will attempt to
execute the binary at the path, or if none exists, gunk will download
the binary to this path.
Add a subcommand to the download command. The user now has to specify
that they want to download protoc. This makes the download command
more flexible, for when we want to use it to download other
protoc-related tools. Allow users to specify the path and version
with the download command as well.
Update the README to reflect the changes and fix miscellaneous
formatting problems while at it.
[OB-367] #done
=> make protoc version, path configurable

go.mod, main_test.go, testdata/scripts/config_protoc.txt
- passing user cache dir variable to testscript
- changes pathversion test to work correctly across OSes
=> fix test config_protoc failures on non Linux OSes

generate/download.go, go.mod
Status codes in the 4xx range don't give an error, so we have to check
for them ourselves. Do that.
For #248.
=> generate: give a better error if download hits a 403

generate/download.go, go.mod, testdata/scripts/config_protoc.txt
to avoid hitting Github API rate limit
Fix #248
=> docgen: remove support for downloading latest version of protoc

loader/loader.go, testdata/scripts/generate_nonexistent_import.txt, testdata/scripts/loader_files.txt
when executing "generate" if an import package is unresolvable, gunk
creates infinite number of gunpkg-*.go files until terminated.
This happens because a recursive calls in Loader.Loop method that
occurs when check.Files returns an error.
Solution: terminate loader.Load if an error is reported.
=> fix infinite loop when generate unresolvable import

scopegen/generate/go.go, testdata/scripts/scopegen.txt, testdata/scripts/scopegen_no_swagger.txt
When generated, current Go const values are separated by commas.
This causes the generated all.scopes.go file to not work properly due to syntax error.
This was easily fixed by removing the comma in the generate file.
=> scopegen: remove commas when generating Go const fields

testdata/scripts/config_protoc.txt
test was failing due to having `XDG_CACHE_HOME` set locally, but not in
the test case, resulting in a discrepancy
sets the env var on the test, and while at it, also includes
`LocalAppData` for windows and `home` for plan9
ref: https://github.com/golang/go/blob/902d5aa84f8340752c20b93bfd450a6cefcf3952/src/os/file.go#L371
fixes #270
=> testdata/scripts: accounts for XDG_CACHE_HOME

docgen/parser/parser.go, testdata/scripts/generate_docgen_map.txt
docgen breaks when encountering a type of map[string/int]value. This commit fixes it by extracting the map fields of a message from the NestedType field of DescriptorProto struct.
=> docgen: fix error when encountering map type

go.mod, go.sum, tools.go
vfsgen is required by `go generate` inside assets, let's add it to tools.go
so it's added to go modules
=> go.mod: add vfsgen to tools and go.mod

generate/generate.go, generate/post_process.go, generate/post_process_json.go, generate/post_process_json_test.go, testdata/scripts/generate_go_json_tag_postproc.txt
Given following gunk code snippet
// Person represents a homo sapien instance.
type Person struct {
FirstName string `pb:"1" json:"first_name"`
LastName string `pb:"2" json:"last_name"`
}
Without `json_tag_postproc` enabled, the output is:
FirstName            string   `protobuf:"bytes,1,opt,name=FirstName,json=first_name,proto3" json:"FirstName,omitempty"`
LastName             string   `protobuf:"bytes,2,opt,name=LastName,json=last_name,proto3" json:"LastName,omitempty"`
With `json_tag_postproc` enabled, the JSON struct tag is fixed to has same value as the the one defined in protobuf tag
FirstName            string   `protobuf:"bytes,1,opt,name=FirstName,json=first_name,proto3" json:"first_name,omitempty"`
LastName             string …
=> protoc-gen-go: add json_tag_postproc option

testdata/scripts/generate_complete_swagger.txt
This PR only added a test case to show how `json_names_for_fields` works.
=> protoc-swagger-gen: add test for json_names_for_fields

testdata/scripts/generate_complete_swagger.txt
This failure happens because @karel-3d PR https://github.com/gunk/gunk/pull/283 got merged before https://github.com/gunk/gunk/pull/287. Both PRs CI passed, but master is failing.
=> generate_complete_swagger: wrong expected value for base path

generate/post_process_json.go, testdata/scripts/generate_go_json_tag_postproc.txt
When post process json tag, skipping struct field with no tag defined.
=> json_tag_postproc: fix panic with gRPC plugin enabled

docgen/parser/parser.go, testdata/scripts/generate_docgen_error_missingfield.txt, testdata/scripts/generate_docgen_error_missingrequest.txt
Currently, we either panic (no request) or return weird error at unrelated place
(when request doesn't have the field).
Fixes https://github.com/gunk/gunk/issues/297
=> docgen: write error when URL field not in request

docgen/parser/parser.go, testdata/scripts/extract.txt, testdata/scripts/extract_annex.txt, testdata/scripts/extract_append.txt, testdata/scripts/extract_code_sample.txt, testdata/scripts/extract_custom_header.txt, testdata/scripts/extract_more_schemes.txt
Currently, the enum description includes the enum type repeated. Let's remove them.
See testscript changes
=> docgen: better enum descriptions

generate/download.go, main_test.go, testdata/scripts/config_protoc.txt, testdata/scripts/download.txt
We were using .cache/home/ under the root of the repository to speed up
incremental test runs, to avoid re-downloading gunk's dependencies at
every test run.
However, this had the major disadvantage of polluting the git checkout,
and leaving read-only files behind, as the Go cache would also end up
there.
Instead, let the tests use the user's real cache directory by default.
Tests which want to use an empty cache set up their own. To simplify
that in a cross-platform way, add a GUNK_CACHE_DIR environment variable.
Overall, the new approach is simpler and tidier.
Fixes #268.
=> all: rework the use of test caches in test scripts

generate/generate.go, testdata/scripts/extract.txt, testdata/scripts/extract_code_sample.txt, testdata/scripts/extract_custom_header.txt, testdata/scripts/extract_more_schemes.txt, testdata/scripts/generate_go_comments.txt
go's ast.TypeSpec.Doc.Text() trims left-trailing spaces on each line of multi-line comment,
while proto's LeadingComments needs them
block comments still look bad, but that's not a priority now
Fixes https://github.com/gunk/gunk/issues/310
=> Proper leading spaces for multi-line comments

dump/dump.go, generate/generate.go, plugin/plugin.go, protoutil/marshal.go, testdata/protoc-gen-strict/main.go
We have large diffs in generated .pb.go files even when there is no change in the protobuf itself. Example:
https://github.com/openbank/openbank/commit/1535696c0f58698898b266dee9bbd4ff144dc874#diff-790a2e5fdb0867ef31e92c5b78946f3c
I found out it's actually caused by non-deterministic marshaling of maps; by default, proto.Marshal is non-deterministic with maps, and grpc uses maps to save response types.
If you actually un-gzip the byte array and diff the filedescriptor, the only changes are in the order of the maps in GRPC.
You can marshal deterministcally using proto.Buffer, so I added a helper func that does that
=> Make .pb.go deterministic by deterministic marshal

docgen/parser/parser.go, testdata/scripts/generate_docgen_only_external.txt
If a request's field comment contains "docgen: hide" string, it is excluded from docgen output.
=> docgen: add ability to hide request parameter

docgen/parser/parser.go, testdata/scripts/generate_docgen_only_external.txt
When filter out the (docgen: hide) in messages, filter it out in all messages instead of only messages on the top level (with name)
=> Fix (docgen: hide) cannot hide nested struct fields

config/config.go, generate/generate.go, generate/post_process.go, go.mod, go.sum, plugin/plugin.go, scopegen/scopegen.go, testdata/scripts/config_protoc.txt, testdata/scripts/extract.txt, testdata/scripts/extract_append.txt, testdata/scripts/extract_code_sample.txt, testdata/scripts/extract_custom_header.txt, testdata/scripts/extract_import.txt, testdata/scripts/extract_more_schemes.txt, testdata/scripts/extract_nested.txt, testdata/scripts/extract_nested_enum.txt, testdata/scripts/generate_complete_swagger.txt, testdata/scripts/generate_docgen_map.txt, testdata/scripts/generate_docgen_only_external.txt, testdata/scripts/generate_go_json_tag_postproc.txt, testdata/scripts/generate_options.txt, testdata/scripts/generate_options_openapiv2.txt
Several fixes that made tests fail.
1. Removed dependency on gogo/protobuf, we used only 2 functions
that are in protobuf already, and they caused random failures.
2. Change underline headers in generated markdown to hash headers
3. New protoc-gen-go fails if we give it unknown flags. This means that
we cannot pass all the options as parameters to it, as we do now.
What that means in practice:
a. don't put `out` as a parameter for protoc-gen-go (and other plugins);
I hope it doesn't break some random plugins somewhere
b. don't put `version` in config_protoc test that does nothing, as it currently fails
c. don't put postproc options to it
4. new swagger returns slightly different output. Changed that in tests.
This should fix all the tests.
=> Fixes after protobuf updates

README.md, config/config.go, generate/download.go, generate/generate.go, generate/post_process.go, main_test.go, testdata/scripts/generate_same_const_names_striperror.txt, testdata/scripts/generate_strip_names.txt, testdata/scripts/old_protocgo_same_const_names.txt
Before, by default gunk removed type names from enums. Unfortunately that makes us stuck with
old version of protoc-gen-go, because new versions don't allow enum clashes.
In order to allow pinning of protoc-gen-go, we need to git-clone the protobuf repo in temp
folder and get the binary from there. But that seems to be working.
I also re-enabled the enum name stripping, but under global option.
=> Pin protoc-gen-go version, enum name stripping

generate/generate.go, reflectutil/setter.go, testdata/scripts/generate_schema.txt
Fix openapi schema option to apply to messages, in order to add
optional data, such as required fields.
Unknown if there is any code depending on the field handling of
JSONSchema, so that has not been disabled.
Taken from
https://github.com/gunk/gunk/pull/326
=> Fix openapi schema

loader/loader.go, testdata/scripts/loader_error_spaces.txt
See the testdata example. Currently, gunk silently ignores these comments.
=> Warn of +gunk comments without declaration

docgen/parser/model.go, docgen/parser/parser.go, testdata/scripts/extract_example.txt
Use like this (also see extract_example.txt)
```
// CreateAccountRequest wraps all required fields for an account creation.
//
// +gunk openapiv2.Schema{
//         Example: `{
//             "foo": "bar"
//         }`,
// }
type CreateAccountRequest struct {
```
=> Use openapiv2 example in docgen requests

docgen/parser/model.go, docgen/parser/parser.go, testdata/scripts/extract_example.txt
value must be a json value (refer to extract_example.txt for more
example)
usage example:
```
// OwnerName is the name of the account's owner.
//
// +gunk openapiv2.Schema{
//         JSONSchema: openapiv2.JSONSchema{
//             Example: `"John Doe"`,
//         },
// }
OwnerName string `pb:"21" json:"owner_name"`
```
=> add support to add example on field level

docgen/parser/parser.go
Sort the fixed example for message to prevent generated example different each time we regenerated even if there is no changes, This is due to iterating over map in go is not specified, so there is no guarantee the iteration order will always be the same. https://golang.org/ref/spec#RangeClause
=> sort message fixed example

loader/loader.go, loader/validate_struct_tags.go, testdata/scripts/generate_wrong_tag.txt, testdata/scripts/loader_import_twice.txt
I have noticed gunk allows invalid (un-terminated) JSON tags,
also it allows double JSON tags and other (never used) tags.
I have copied over the go vet code to check correct tags.
=> Validate field tags

loader/validate_struct_tags.go, testdata/scripts/generate_disallowed_tag.txt
In our large codebase with gunk, we have introduces some errors by wrong tags.
Add checks for that in gunk, so it does not silently ignore it.
=> Check that field tags only have pb and json

docgen/templates/api.md
This updates the authorization method of the docgen-generated api
documentation from Bearer token to API Key.
=> docgen: update auth template

go.mod, plugin/go.mod, plugin/go.sum, plugin/plugin.go
so it could be imported into docgen/scopegen separate repos
without introducing dependency to whole gunk.
Removed dependency from plugin to protoutil; as we don't
actually need to be deterministic there.
=> Separate plugin/ to a separate module,

loader/validate_struct_tags.go, testdata/scripts/generate_disallowed_omitempty.txt
The go vet check includes check for space after comma, which makes sense in
go vet, as it catches `json:"foo, omitempty"`. However I simplified the code here
and include a bug, where JSON cannot have a space in name.
I have instead changed this to checking for comma, as we do not allow `json:"foo,omitempty"` anyway.
=> Replace space check for comma check

main.go
Gunk now only shows the error occured, and 'Run '[cmd] --help' for usage'.
This helps reduce the amount of information users see when inputting
incorrect information.
=> fix: Don't show full usage when command is wrong

format/format.go
Calling `gunk format -` Will read for a single gunk source file from stdin, and then write the formatted version to stdout. This has the added benefit of being able to call it from my editor automatically via a plugin, (on save).
=> feat: Allow calling `gunk format` from stdin.

config/config.go, generate/downloader/protoc.go, testdata/scripts/config_error.txt, testdata/scripts/config_protoc.txt
With this PR, config validates that no commands may override the generator specified in the section header and the language-specific options are specified in their relevant languages only.
It also makes the error message clearer when the user did not specify "v" in their version and provided a path.
Before: `want protoc version ".8.0" got "3.8.0"`
After: `want protoc version "3.8.0" got "v3.8.0"`
=> Provide clearer error messages in config and downloader

loader/loader.go, testdata/scripts/generate_errors.txt
This PR handles import loops in `loader` and removes redundant `-:`s from the error messages by not wrapping the error if possible.
=> loader: Handle import loops and simplify error messages

loader/loader.go, testdata/scripts/generate_name_conflict.txt
This allows compilation to succeed even if the Gunk package name has changed if the generated files are in the same directory.
=> loader: allow package name mismatch on Go files

config/config.go, loader/loader.go, testdata/scripts/config_projectroot.txt
Currently packages are just being dropped when they error because the Errors field is not being checked.
This causes problems when packages that are imported fail to compile.
This PR fixes it by printing the error out and reporting to the caller.
=> WIP: loader: Handle package-loading errors

lint/json.go, lint/lint.go, testdata/scripts/lint_json.txt
This allows the JSON linter to be consistent with the formatter.
=> lint: Add initialisms support for JSON linter

generate/doc/doc.go, generate/doc/json.go
Only JSON names are exposed in the generated JSON. Therefore, this
commit filters the names in the path to their JSON names before passing
it to the frontend.
This allows the frontend to distinguish between path parameters and
query parameters.
=> generate: Filter path parameters

README.md, generate/downloader/download.go, generate/downloader/ts.go
This is to make it possible to generate protobuf in pure
Typescript file which can be used as ES Module like when using
with [Vite](https://vitejs.org).
Issue #365
=> feat (generate): Add capability to output as Typescript ES Module
