- loader/loader.go
This is more reliable, for example if one declares two parameters
sharing the same type node.
While at it, use better names for some fields and funcs.
> use go/types for parameter lists

- loader/loader.go
Now that we have the gunkPackage structure, we can just fit the extra
package information there.
While at it, document why we don't want to refer to proto files by
absolute paths when sending the data to the generators.
> loader: fold three maps by package path into one

- generate/generate.go
- loader/loader.go
Since it's not exclusive to code generation.
> loader: move loading proto deps to this package

- generate/generate.go
- generate/proto.go
- loader/loader.go
Since other commands like fmt will also need it.
> loader: move gunk tag parsing here

- go.mod
- go.sum
Update the ini dependency now that is supports handling multiple
sections of the same name and getting keys correctly from those
sections.
> mod: updated the ini dependency

- config/config.go
Added a 'DefaultConfig' in the config package. This will run
'protoc-gen-go' and 'protoc-gen-grpc-gateway' by default. The
'DefaultConfig' will be used if no '.gunkconfig' can be foung in the
current directory, or any parent directories.
> config: add a default config

- convert/convert.go
- format/format.go
Add format.Source for this use case, mirroring the function signature in
go/format.
Fixes #60.
> convert: run result through the formatter

- examples/util/doc.go
- testdata/generate/doc.go
- testdata/generate/imported-notarg/doc.go
- testdata/generate/imported/doc.go
I forgot about the ones on disk, outside of the scripts.
> all: remove last doc.go files

- generate/generate.go
- main_test.go
- testdata/scripts/cmds.txt
While add it, add a simple 'gunk version' test, since there was none.
> all: make unparam happy

- generate/generate.go
Generators directly within protoc insist on writing the files
themselves, so we must give it a CodeGeneratorRequest that has been
modified to contain the right paths.
However, we were doing this in a very roundabout way. We did it for all
generators, and we used a map, which is unnecessary.
The actual logic only requires about ten lines of code in
generateProtoc. We can remove over fifty lines, thanks to that.
The other piece that the old code did was replace ".gunk" with ".proto".
However, all packages are generated as a single "all.proto" file now, so
that line had been a no-op for a while.
> generate: greatly simplify file descriptor sets

- assets/doc.go
- config/config.go
- loader/loader.go
It's mostly unhappy about the lack of godocs, but some of the warnings
are good tips.
> all: make golint happier

- loader/proto.go
- testdata/scripts/convert_comment.txt
> loader: add convert comment

- go.mod
- go.sum
- loader/proto.go
- testdata/scripts/convert_complete_swagger.txt
- Handle complete swagger definition for convert command
> convert: add swagger object

- generate/generate.go
- loader/proto.go
- reflectutil/setter.go
This supports both proto and go/ast as values, so we can remove over 300
lines of boilerplate code.
> reflectutil: support structs and slices in SetValue

- generate/generate.go
- loader/proto.go
- reflectutil/setter.go
This removes the remaining boilerplate code from loader and generate.
> reflectutil: start exposing Unmarshal APIs

- generate/download.go
Does a little bit of cleaning up with regards to downloading from
GitHub. Now always downloads latest available release.
> download: cleanup how protoc releases are retrieved from github

- .travis.yml
> enable test for macOS

- reflectutil/setter.go
- testdata/scripts/convert_options_openapiv2_schema.txt
> fix gunk convert panic when option contains []byte value

- docgen/docgen.go
- docgen/generate/generate.go
- docgen/parser/model.go
- docgen/parser/parser.go
- generate/generate.go
- main_test.go
- testdata/scripts/extract_import.txt
Edited the docgen plugin to properly add the documentation for imported Messages (structs). Also fixed a bug where docgen didn't generate for files that have imports
> update docgen  for dependency importing

- docgen/parser/parser.go
- loader/loader.go
- testdata/scripts/generate_anonymous_struct_error.txt
Made gunk reject anonymoius/unamed attributes and added a human friendly error message when encountered. Also ran gofmt
> fixed crash when encountering anonymous struct attributes

- loader/loader.go
- testdata/scripts/format.txt
creates a new error kind for proto name mismatch
adds a helper func to remove the error kind from []*loader.GunkPackage
fixes #265
> format: allow receiving files from different packages

- generate/download.go
Before this patch 'sudo rm -rf .cache && go test ./...' would result in
lots of errors like:
error: error executing "[...]/protoc-v3.9.1": [...]: text file busy
This was because we were using the binary itself as the file being
locked. Because the lock was grabbed with write access, and many
operating systems like Linux forbid executing a binary that's open for
writing, we were seeing data races when downloading.
Here's a description of the chain of events that could lead to a race
between two tests, assuming the empty cache:
Test A: finds protoc is missing, locks the binary for writing
Test B: finds protoc is missing, locks the binary for writing
Test A: wins the race for the lock, begins downloading protoc
Test B: loses the race for the lock, blocks
Test A: finishes the download, closes …
> generate: use a separate lock file when downloading protoc

- docgen/parser/parser.go
- testdata/scripts/extract_nested_enum.txt
currently, we extract only enums from the same file, not from dependencies. See the new test.
> docgen: extract enums from dependencies into annex

- assets/wat
Sorry about that, I added temp file by mistake in the generated code directory.
> Remove forgotten temp file

- docgen/docgen.go
- docgen/generate/generate.go
- docgen/parser/parser.go
- testdata/scripts/generate_docgen_whitelist.txt
to allow to skip all method not tagged with "external"
> docgen: add only_external option

- loader/proto.go
- testdata/scripts/convert_orphan_comment.txt
> Fix orphan comment

- README.md
- generate/downloader/download.go
- generate/downloader/grpc-python.go
- generate/downloader/swift.go
- generate/generate.go
- main.go
Taken from https://github.com/gunk/gunk/pull/326
> Add support for python grpc, fix paths

- generate/downloader/grpc-ecosystem.go
- generate/downloader/grpc-java.go
- generate/downloader/protoc.go
> Use rosetta on M1 macs

- generate/generate.go
Currently, generators cannot create folders;
and, if the generators use package import path in resp.File.Name,
it will also not match any folder.
Fix both to allow easier creation of subfolders.
> Allow generators to create sub-folders

- testdata/scripts/extract.txt
- testdata/scripts/extract_append.txt
- testdata/scripts/extract_code_sample.txt
- testdata/scripts/extract_custom_header.txt
- testdata/scripts/extract_example.txt
- testdata/scripts/extract_import.txt
- testdata/scripts/extract_more_schemes.txt
- testdata/scripts/extract_nested.txt
- testdata/scripts/extract_nested_enum.txt
- testdata/scripts/extract_skip_comma.txt
- testdata/scripts/generate_docgen_map.txt
- testdata/scripts/generate_docgen_only_external.txt
As we changed the authorization to use apikey, we need to change the
desired behavior for it on its testcases.
> docgent: update testdata to use apikey

- README.md
- config/config.go
- examples/util/echo.gunk
- format/format.go
- go.mod
- go.sum
- testdata/scripts/format.txt
- testdata/scripts/format_missingnumbers.txt
- testdata/scripts/format_options.txt
- testdata/scripts/loader_files.txt
This PR adds a config section for `format` which allows enabling automatically setting JSON and pb tags.
> format: Automatically set JSON and PB

- lint/commentstart.go
- lint/json.go
- lint/lint.go
- lint/unimport.go
- lint/unused.go
- main.go
- testdata/scripts/lint_commentstart.txt
- testdata/scripts/lint_json.txt
- testdata/scripts/lint_unused.txt
This PR adds a linter to gunk which can be executed using `gunk lint [pattern]`.
> lint: Add linter

- config/config.go
As doc is no longer built-in, this PR removes related special cases
in config.
> cleanup(config)!: Remove doc-related config parsing

- generate/downloader/protoc.go
- go.mod
> Fix version checks for protoc 21+, download ARM binary on mac if possible

- generate/generate.go
Protobuf CodeGeneratorRequests keep track of comment metadata for
definitions seperate from the type definitions themselves, through
indices relative to the definitions in FileDescriptorProto.ProtoFile.
When an item is ignored, all subsequent subfields and sub definitions
need to have their paths respect ignored fields, so that comments can
still be correctly read from protoc generators.
This is fixed by only adding relevant comments to pruned
CodeGeneratorRequests and evaluating their paths at time of pruning so
that they stay in sync.
Another minor change made is that ProtoFiles contained in the
CodeGeneratorRequest that don't have any ignored items are skipped
completely, potentially helping performance in situations where there
are lots of files where there is nothing being ignored, …
> fix: Keep comment indices in sync when items are ignored.
